name: ItemEditor
api: 5.3.0
main: frostcheat\itemeditor\ItemEditor
author: FrostCheat
version: 1.0.0

permissions:
  itemeditor.command:
    description: Main permission for /ie
    default: op
  itemeditor.command.amount:
    description: Permission for command /ie amount
    default: op
  itemeditor.command.edit:
    description: Permission for command /ie edit
    default: op
  itemeditor.command.help:
    description: Permission for command /ie help
    default: op
  itemeditor.command.reopen:
    description: Permission for command /ie reopen
    default: op
  itemeditor.command.rename:
    description: Permission for command /ie reopen
    default: op
  itemeditor.command.repair:
    description: Permission for command /ie repair
    default: op
  itemeditor.command.unbreakable:
    description: Permission for command /ie unbreakable
    default: op